name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: make bindings

    - name: Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: NuGet
        path: .build/NuGet/*.nupkg
