name: Build

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  Build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Workloads
      run: |
        dotnet workload install maui ios maccatalyst android tvos macos

    - name: Build
      run: make binding

    - name: Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: NuGet
        path: .build/NuGet/*.nupkg

  Publish:
    runs-on: macos-latest
    needs: Build
    if: github.event_name == 'release'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: NuGet
      - name: Publish NuGet
        run: |
          dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/redth/index.json"
          dotnet nuget push "NuGet/*.nupkg" --source "github"
